// This file is generated by Slice Machine. Update with care!

import Card from './Card'
import Form from './Form'
import ImageSlice from './ImageSlice'
import Infobox from './Infobox'
import Partner from './Partner'
import Quote from './Quote'
import Stage from './Stage'
import Text from './Text'
import TextImage from './TextImage'
import Video from './Video'

export { Card, Form, ImageSlice, Infobox, Partner, Quote, Stage, Text, TextImage, Video }

export const components = {
  card: Card,
  form: Form,
  imageSlice: ImageSlice,
  infobox: Infobox,
  partner: Partner,
  quote: Quote,
  stage: Stage,
  text: Text,
  text_image: TextImage,
  video: Video,
}
